version: '3.8'
services:
    postgres:
        image: apache/airflow:postgres-11
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
    scheduler:
        image: apache/airflow:1.10.12-python3.6
        command: scheduler
        restart: always
        depends_on:
            - webserver
        env_file:
            - .env
        volumes:
            - $FILES_PATH/dags:/opt/airflow/dags
            # - $FILES_PATH/logs:/opt/airflow/logs
    webserver:
        image: apache/airflow:1.10.12-python3.6
        entrypoint: ./scripts/entrypoint.sh
        restart: always
        depends_on:
            - postgres
        env_file:
            - .env
        volumes:
            - $FILES_PATH/dags:/opt/airflow/dags
            # - $FILES_PATH/logs:/opt/airflow/logs
            - $INSTALL_PATH/scripts:/opt/airflow/scripts
        ports:
            - "8080:8080"
